services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 3000:3000 # App port
      # - 2345:2345 # Delve debugger port
    volumes:
      - .:/usr/src/app
    command: air cmd/server/main.go -b 0.0.0.0
    # command: >
    #   sh -c "
    #     dlv exec ./server --headless --listen=0.0.0.0:2345 --api-version=2 --accept-multiclient --log &
    #     air cmd/server/main.go -b 0.0.0.0
    #   "
    # depends_on: # Extra
    #   - db
    # command: dlv exec ./app --headless --listen=:2345 --api-version=2 --accept-multiclient --log

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5431:5432
    volumes:
      - pg-db:/var/lib/postgresql/data

volumes:
  pg-db:
