services:
  server:
    build: .
    env_file:
      - .env
    ports:
      - 5001:5001 # App port
    volumes:
      - .:/usr/src/app
    command: air main.go -b 0.0.0.0

  db:
    image: postgis/postgis:17-3.5
    platform: linux/amd64
    # image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5431:5432
    volumes:
      - pg-db:/var/lib/postgresql/data

volumes:
  pg-db:
