// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},"swagger":"2.0","info":{"description":"{{escape .Description}}","title":"{{.Title}}","contact":{},"version":"{{.Version}}"},"host":"{{.Host}}","basePath":"{{.BasePath}}","paths":{"/health":{"get":{"description":"This endpoint checks api health.","consumes":["application/json"],"produces":["application/json"],"tags":["Health"],"summary":"Health Check","responses":{"200":{"description":"OK","schema":{"$ref":"#/definitions/dto.SendSuccess"}},"401":{"description":"Unauthorized","schema":{"$ref":"#/definitions/dto.SendError"}},"429":{"description":"Too Many Requests","schema":{"$ref":"#/definitions/dto.SendError"}}}}}},"definitions":{"dto.SendError":{"type":"object","properties":{"errors":{"type":"array","items":{"type":"string"},"example":["Unexpected issue"]},"message":{"type":"string","example":"Failed"},"success":{"type":"boolean","example":false}}},"dto.SendSuccess":{"type":"object","properties":{"data":{},"message":{"type":"string","example":"Successfull"},"success":{"type":"boolean","example":true}}}}}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Backend Service API",
	Description:      "API documentation for Khajuraho API Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
