basePath: /api/v1
definitions:
  dto.SendError:
    properties:
      errors:
        example:
        - Unexpected issue
        items:
          type: string
        type: array
      message:
        example: Failed
        type: string
      success:
        example: false
        type: boolean
    type: object
  dto.SendSuccess:
    properties:
      data: {}
      message:
        example: Successfull
        type: string
      success:
        example: true
        type: boolean
    type: object
host: localhost:5001
info:
  contact: {}
  description: API documentation for Khajuraho API Service
  title: Backend Service API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: This endpoint checks api health.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.SendSuccess'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.SendError'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/dto.SendError'
      summary: Health Check
      tags:
      - Health
swagger: "2.0"
