info:
  contact: {}
  description: API documentation for Bonus Service
  title: Backend Service API
  version: "1.0"
paths:
  /api/v1/auth/send-otp:
    get:
      consumes:
      - application/json
      description: This endpoint sends OTP.
      produces:
      - application/json
      responses:
        "204":
          description: OTP successfully sent
      summary: Send OTP
      tags:
      - OTP
swagger: "2.0"
